_target_: models.components.conditional_density.LearnedDiffusionConditional

_partial_: true

defaults:
  - /model/components@joint_policy: JointPolicy-PIS

  - /model/components@langevin_scaler: LangevinScaling-PIS

sample_dim: ${energy.dim}

joint_policy:
  s_dim: ${energy.dim}

langevin_scaler:
  out_dim: 1

clipping: true
lgv_clip: 1e2
gfn_clip: 1e4

learn_variance: false

base_std: 1.0
