_target_: models.AnnealedGFN

defaults:
  - components@state_encoder: StateEncoding-PIS

  - components@time_encoder: TimeEncoding-PIS

  - components@flow_model: FlowModel-PIS

  - components@forward_policy: JointPolicy-PIS

  - components@backward_policy: JointPolicy-PIS

  - components@langevin_scaler: LangevinScaling-PIS

  - prior_energy: Gaussian

state_encoder:
  s_dim: ${energy.dim}

trajectory_length: 100

forward_policy:
  s_dim: ${energy.dim}

backward_policy:
  s_dim: ${energy.dim}

langevin_scaler:
  _partial_: true
  out_dim: 1

clipping: true
lgv_clip: 1e2
gfn_clip: 1e4

learn_variance: false

log_var_range: 4.0
base_std: 1.0

fixed_logZ_ratio: false

optimizer_cfg:
  lr_policy: 1e-3
  lr_flow: 1e-1
  weight_decay: 1e-7
  use_weight_decay: false
  max_grad_norm: null
