_target_: models.CMCDSampler

defaults:
  - components@state_encoder: StateEncoding-PIS

  - components@time_encoder: TimeEncoding-PIS

  - components@control_model: JointPolicy-PIS

  - prior_energy: Gaussian

control_model:
  s_dim: ${energy.dim}

state_encoder:
  s_dim: ${energy.dim}

trajectory_length: 100

base_diffusion_rate: 1.0

clipping: true
lgv_clip: 1e2
gfn_clip: 1e4

optimizer_cfg:
  lr_policy: 1e-3
  lr_flow: 1e-1
  weight_decay: 1e-7
  use_weight_decay: false
