_target_: sampler.gfn.models.DoubleGFN

defaults:
  - prior_energy: Gaussian

  - /model@first_gfn: AnnealedGFN
  - /model@second_gfn: AnnealedGFN

first_gfn:
  _partial_: true
  flow_model: null

second_gfn:
  _partial_: true
  flow_model: null

trajectory_length: 200

optimizer_cfg: null