_target_: models.gfn.GFN

trajectory_length: 100

s_emb_dim: 64
hidden_dim: 64
harmonics_dim: 64
t_dim: 64

t_scale: 1.0

langevin: false
langevin_scaling_per_dimension: true

learned_variance: false
log_var_range: 4.0

learn_pb: false
pb_scale_range: 0.1

partial_energy: false

clipping: true
lgv_clip: 1e2
gfn_clip: 1e4

conditional_flow_model: false

pis_architectures: true
lgv_layers: 3
joint_layers: 2
zero_init: true