seed: 12345

device: "cuda:0"

defaults:
  - energy: manywell
  - model: GFN
  - train: OnPolicy
  - _self_

  # Experiments config file can override the default option.
  - experiment: GFN/OnPolicy/TB+Expl

train:
  trainer:
    _recursive_: false
  device: ${device}

model:
  device: ${device}

energy:
  device: ${device}

eval:
  eval_every_n_epoch: 100
  save_model_every_n_epoch: 1000

  eval_data_size: 2000
  final_eval_data_size: 2000
  plot_sample_size: 2000

wandb:
  project: "GFN Energy"