seed: 12345

device: "cuda:0"

defaults:
  - energy: manywell
  - model: gfn
  - train: gfn_train
  - _self_
  - experiments: TB_with_ground_truth_sample

train:
  trainer:
    _recursive_: false
  device: ${device}

model:
  device: ${device}

energy:
  device: ${device}

eval:
  eval_every_n_epoch: 100
  save_model_every_n_epoch: 1000

  eval_data_size: 2000
  final_eval_data_size: 2000
  plot_sample_size: 2000

wandb:
  project: "GFN Energy"