seed: 12345

device: "cuda:0"

defaults:
  - energy: ManyWell
  - model: GFN-PIS
  - _self_

model:
  device: ${device}

energy:
  device: ${device}

name: ???

hydra:
  help:
    app_name: "Sampler model profiler"

    header: ""

    footer: ""

    template: |-
      This is profiler for sampler model. 
      Specifically, it measures the time taken for one training step for the model.
      Here, one_training_step = get_forward_trajectory + back propagation

      Usage: python3 profiler/profile-model.py name=(model name you want to profile)
