# @package _global_

energy:
  _target_: energy.many_well.ManyWell
  dim: 32

eval:
  plot:
    plotting_bounds: [-3.0, 3.0]
    projection_dims: [[0, 2], [1, 2], [2, 4], [3, 4], [4, 6], [5, 6]]
    fig_size: [12, 20]
