trainer:
  _target_: sampler.gfn.trainer.sequential_trainer.SequentialTrainer

defaults:
  - /train@subtrainer: OnPolicy

stage: null
model_path: null

epochs: 25000
batch_size: 300

subtrainer:
  batch_size: ${train.batch_size}
  _recursive_: false